void Rapidity_fit()
{
//=========Macro generated from canvas: c/
//=========  (Mon Jul 18 17:09:21 2016) by ROOT version6.02/05
   TCanvas *c = new TCanvas("c", "",0,0,700,500);
   gStyle->SetOptStat(0);
   c->Range(-0.875,-3.532624,6.069444,12.8115);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLeftMargin(0.126);
   c->SetRightMargin(0.154);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1F *t1_data_jpsi_DeltaRapidityA1 = new TH1F("t1_data_jpsi_DeltaRapidityA1","CMS 2015  #sqrt{s} = 13 TeV  L_{int} = 2.83 fb^{-1}",10,0,5);
   t1_data_jpsi_DeltaRapidityA1->SetBinContent(1,3.767442);
   t1_data_jpsi_DeltaRapidityA1->SetBinContent(2,7.767442);
   t1_data_jpsi_DeltaRapidityA1->SetBinContent(3,3.162791);
   t1_data_jpsi_DeltaRapidityA1->SetBinContent(4,-0.5581396);
   t1_data_jpsi_DeltaRapidityA1->SetBinContent(5,-0.2790698);
   t1_data_jpsi_DeltaRapidityA1->SetBinContent(6,-0.2790698);
   t1_data_jpsi_DeltaRapidityA1->SetEntries(13.5814);
   t1_data_jpsi_DeltaRapidityA1->GetXaxis()->SetTitle("#mu#mu_{1} L_{XY} [cm]");
   t1_data_jpsi_DeltaRapidityA1->GetXaxis()->SetLabelFont(42);
   t1_data_jpsi_DeltaRapidityA1->GetXaxis()->SetLabelSize(0.035);
   t1_data_jpsi_DeltaRapidityA1->GetXaxis()->SetTitleSize(0.035);
   t1_data_jpsi_DeltaRapidityA1->GetXaxis()->SetTitleFont(42);
   t1_data_jpsi_DeltaRapidityA1->GetYaxis()->SetTitle("Events/0.04 GeV");
   t1_data_jpsi_DeltaRapidityA1->GetYaxis()->SetLabelFont(42);
   t1_data_jpsi_DeltaRapidityA1->GetYaxis()->SetLabelSize(0.035);
   t1_data_jpsi_DeltaRapidityA1->GetYaxis()->SetTitleSize(0.035);
   t1_data_jpsi_DeltaRapidityA1->GetYaxis()->SetTitleOffset(0.94);
   t1_data_jpsi_DeltaRapidityA1->GetYaxis()->SetTitleFont(42);
   t1_data_jpsi_DeltaRapidityA1->GetZaxis()->SetLabelFont(42);
   t1_data_jpsi_DeltaRapidityA1->GetZaxis()->SetLabelSize(0.035);
   t1_data_jpsi_DeltaRapidityA1->GetZaxis()->SetTitleSize(0.035);
   t1_data_jpsi_DeltaRapidityA1->GetZaxis()->SetTitleFont(42);
   t1_data_jpsi_DeltaRapidityA1->Draw("Ep");
   
   TH1F *Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2 = new TH1F("Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2","CMS 2015  #sqrt{s} = 13 TeV  L_{int} = 2.83 fb^{-1}",10,0,5);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(1,3.985159);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(2,6.877481);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(3,3.344247);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(4,0.5420709);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(5,0.1068187);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(6,1.682463e-12);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(7,9.330967e-13);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(8,5.479838e-13);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(9,1.46022e-13);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetBinContent(10,1.604638e-15);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->SetEntries(10);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *AText = ptstats->AddText("t1_data_jpsi_DeltaRapidityA");
   AText->SetTextSize(0.0368);
   AText = ptstats->AddText("Entries = 14     ");
   AText = ptstats->AddText("Mean  = 0.6147");
   AText = ptstats->AddText("RMS   = 0.2455");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetXaxis()->SetTitle("|#Delta y|");
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetXaxis()->SetLabelFont(42);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetXaxis()->SetLabelSize(0.035);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetXaxis()->SetTitleSize(0.035);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetXaxis()->SetTitleFont(42);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetYaxis()->SetTitle("Events/0.5 GeV");
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetYaxis()->SetLabelFont(42);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetYaxis()->SetLabelSize(0.035);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetYaxis()->SetTitleSize(0.035);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetYaxis()->SetTitleFont(42);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetZaxis()->SetLabelFont(42);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetZaxis()->SetLabelSize(0.035);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetZaxis()->SetTitleSize(0.035);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->GetZaxis()->SetTitleFont(42);
   Fraction fit to hist: t1_data_jpsi_DeltaRapidityA2->Draw("same");
   
   TLegend *leg = new TLegend(0.4,0.6,0.8,0.75,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("t1_data_jpsi_DeltaRapidityA","DATA (After subtraction)","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Fraction fit to hist: t1_data_jpsi_DeltaRapidityA","Combined model (DPS + SPS)","FL");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.93,0.935,1.47,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.15,0.9163333,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   AText = pt->AddText("CMS 2015  #sqrt{s} = 13 TeV  L_{int} = 2.83 fb^{-1}");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
